server:
  port: 8080
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: H2
  datasource:
    schema: classpath:schema.sql
    data: classpath:data.sql
    url: jdbc:h2:mem:soa_service_api
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
